### ISSUE TITLE
Прыгающий скролл при закрытии попапа

### ISSUE THREAD

**Issue by foxhable** [aaccent/loginov_layout#10]
После закрытия попапа происходит скролл с верха страницы до блока

<details><summary>Гифка (Может долго раскрываться)</summary>

![flickeringbug](https://github.com/aaccent/loginov_layout/assets/36298346/ddbb2d35-1176-4d42-a352-823ae971e4a8)
</details>

**Comment by foxhable** [comment]
Тоже самое и на пк с попапами

**Comment by EduardoAlparov** [comment]
Исправлено, нужно проверить
