### ISSUE TITLE
Хлебные крошки

### ISSUE THREAD

**Issue by foxhable** [aaccent/loginov_layout#12]
1. Хлебные крошки при скроле не должны быть видны

<details><summary>Скрин</summary>

![image](https://github.com/aaccent/loginov_layout/assets/36298346/500cc66b-d359-481d-8223-f7b726975c36)
</details> 

---

2. Хлебные крошки поверх мобильного меню

<details><summary>Скрин</summary>

![image](https://github.com/aaccent/loginov_layout/assets/36298346/b681a3af-2921-436c-bc81-6664333786b4)
</details>

**Comment by EduardoAlparov** [comment]
Исправлено, нужно проверить

**Comment by foxhable** [comment]
Если на мобилке проскролить вниз и вернутся, то крошки не появятся

<details><summary>Гифка</summary>

![breadcrumbs-bug](https://github.com/aaccent/loginov_layout/assets/36298346/00ebcbc2-98fc-4668-a20d-7c947a9fc4c2)
</details>

**Comment by EduardoAlparov** [comment]
Исправлено, нужно проверить
