### ISSUE TITLE
Первый блок страницы "О компании"

### ISSUE THREAD

**Issue by foxhable** [aaccent/loginov_layout#13]
Наложенность фотографий не та

<details><summary>Разница</summary>

![image](https://github.com/aaccent/loginov_layout/assets/36298346/4359053c-63a2-4ff9-8cf5-cf2eb827ca6f)
</details> 

<details><summary>Скрин с блоком</summary>

![image](https://github.com/aaccent/loginov_layout/assets/36298346/4048b22c-455e-4504-8348-5c71fc4568ee)
</details>

**Comment by EduardoAlparov** [comment]
Исправлено, нужно проверить
