### ISSUE TITLE
Первый блок "О компании" на мобилке

### ISSUE THREAD

**Issue by foxhable** [aaccent/loginov_layout#14]
1. Стартовая позиция текста "loginov.agency" не та

<details><summary>Скрин</summary>

![image](https://github.com/aaccent/loginov_layout/assets/36298346/afcd583e-bada-4bfe-a629-e0536b60ef5d)
</details> 

---

2. Текст "Профессиональные юристы" должен быть размером `18px`

<details><summary>Скрин</summary>

![image](https://github.com/aaccent/loginov_layout/assets/36298346/0d8ed332-5fa8-4deb-8e20-0f79c245f776)
</details>

**Comment by EduardoAlparov** [comment]
Исправлено, нужно проверить
