### ISSUE TITLE
Блок "Ответы на вопросы"

### ISSUE THREAD

**Issue by foxhable** [aaccent/loginov_layout#17]
Нижний `padding` и `gap` между элементами создают вместе большее расстояние, чем нужно

<details><summary>Скрин</summary>

![image](https://github.com/aaccent/loginov_layout/assets/36298346/079e6923-feb8-4947-9e4d-f947c8b0fb4b)
</details>

**Comment by EduardoAlparov** [comment]
Исправлено, нужно проверить
