### ISSUE TITLE
Страница "Наши кейсы"

### ISSUE THREAD

**Issue by foxhable** [aaccent/loginov_layout#19]
1. Заголовок должен быть "Наши кейсы", а не "Наш опыт"

---

2. У элемента списка картинка в мобилке должна быть `60px`

<details><summary>Скрин</summary>

![image](https://github.com/aaccent/loginov_layout/assets/36298346/50aefa8a-0395-49c6-a69f-33473d763883)
</details> 

--- 
3. Серый текст у элементов не должен сокращаться

<details><summary>Скрин</summary>

![image](https://github.com/aaccent/loginov_layout/assets/36298346/b6aa07a6-e2a6-4028-8fbb-fd09b12650b6)
</details>

**Comment by EduardoAlparov** [comment]
Исправлено, нужно проверить
