### ISSUE TITLE
Страница проекта

### ISSUE THREAD

**Issue by foxhable** [aaccent/loginov_layout#20]
1. Отступ снизу заголовка страницы на мобилке должен быть `20px`

<details><summary>Скрин</summary>

![image](https://github.com/aaccent/loginov_layout/assets/36298346/acca0fd5-c2a3-49db-b592-f7529c0aa40a)
</details>

**Comment by EduardoAlparov** [comment]
Исправлено, нужно проверить

**Comment by EduardoAlparov** [comment]
Исправлено, нужно проверить
