### ISSUE TITLE
Видео в статье

### ISSUE THREAD

**Issue by foxhable** [aaccent/loginov_layout#21]
1. Нету наложенного плеера на видео

<details><summary>Скрин</summary>

![image](https://github.com/aaccent/loginov_layout/assets/36298346/9d4f868a-13b4-45e7-a1d8-5c84d41bdbba)
</details> 
 
--- 

2. `videoId` должен браться из `data-*` атрибута. Их как-то нужно вставлять контент менеджерам - атрибут в этом поможет.

Должно выглядеть примерно так

```html
<div class="video" data-youtube-id="lJIrF4YjHfQ"></div>
```

https://github.com/aaccent/loginov_layout/blob/5fbbd31a63f3d047c7335bb2068e2f5b9dc8f8de/js/modules/youtubeVideoControl.js#L10-L21

---

3. Лучше сделать не по id, а по классу, т.к. на странице в теории может быть несколько разных видео.

**Comment by EduardoAlparov** [comment]
Исправлено, нужно проверить

**Comment by foxhable** [comment]
Затемнения нету

**Comment by EduardoAlparov** [comment]
Исправлено, нужно проверить
