### ISSUE TITLE
Секция `presentation` в safari

### ISSUE THREAD

**Issue by foxhable** [aaccent/loginov_layout#26]
На мобилке сафари элемент `.presentation__image-block` не в полную ширину, добавь ему `width: 100%`

<details><summary>Скрин</summary>

![image](https://github.com/aaccent/loginov_layout/assets/36298346/b011a293-07ca-4e53-aa66-ac13de641266)
</details>

**Comment by EduardoAlparov** [comment]
Исправлено, нужно проверить
