### ISSUE TITLE
Сео блок на safari

### ISSUE THREAD

**Issue by foxhable** [aaccent/loginov_layout#27]
`line-clamp` не работает с `display: block` элементами в детях. Нужно `p` элементы в `.seo-section__text` сделать `display: inline`. О проблеме на [стаковерфлоу](https://stackoverflow.com/a/72170897)

<details><summary>Скрин</summary>

![image](https://github.com/aaccent/loginov_layout/assets/36298346/083498cc-447b-477b-97c0-80599d54b8a6)
</details>

**Comment by EduardoAlparov** [comment]
C "inline" не работает, только с "inline-block".

**Comment by EduardoAlparov** [comment]
Исправлено, нужно проверить

**Comment by foxhable** [comment]
Не, для сафари обязательно `inline`. А что не работает? Ты про пропажу расстояний между элементами?

**Comment by EduardoAlparov** [comment]
Странное поведение, на последней версии safari вроде норм работает.
Исправил, нужно проверить.

**Comment by foxhable** [comment]
Ладно, хер с ним, пусть так
