### ISSUE TITLE
Стили `button` в сафари

### ISSUE THREAD

**Issue by foxhable** [aaccent/loginov_layout#28]
В сафари цвет текста у кнопок синий по умолчанию. Добавь на `button` `color: inherit`;

<details><summary>Скрин</summary>

![image](https://github.com/aaccent/loginov_layout/assets/36298346/c9742f92-61e8-41ed-a28c-ddfffcdf933a)
</details>

**Comment by EduardoAlparov** [comment]
Исправлено, нужно проверить
