### ISSUE TITLE
Фиксирование шапки

### ISSUE THREAD

**Issue by foxhable** [aaccent/loginov_layout#29]
Работает не так, как ожидается. Нужно, чтобы шапка пропадала при скроле вниз и появлялась при небольшом скроле вверх в любом месте документа. Сейчас она появляется только если просколить вверх в конкретном месте и иногда не пропадает. Это касается мобилки и пк.

[Видео с багом](https://github.com/aaccent/loginov_layout/assets/36298346/bd7c2516-f242-4961-af3a-5255db922e76)

**Comment by EduardoAlparov** [comment]
Исправил, нужно проверить.
