### ISSUE TITLE
Анимация чисел

### ISSUE THREAD

**Issue by foxhable** [aaccent/loginov_layout#3]
Анимация начинается рано, цифры находятся почти в конце блока, а тригер в самом начале.

Лучше число вытягивать из документа, а не хардкодить, иначе придется каждый год редактировать скрипт, если они захотят поддерживать это значение актуальным
https://github.com/aaccent/loginov_layout/blob/5fbbd31a63f3d047c7335bb2068e2f5b9dc8f8de/js/modules/autoCounterAnimatiion.js#L14

![image](https://github.com/aaccent/loginov_layout/assets/36298346/46b3a5c1-980a-427a-b2b3-ad0710529ca1)

**Comment by EduardoAlparov** [comment]
Исправлено, нужно проверить

**Comment by foxhable** [comment]
Нужно сделать для обоих чисел, не только для годов, но и для количества клиентов

**Comment by EduardoAlparov** [comment]
Исправлено, нужно проверить
