### ISSUE TITLE
Меню

### ISSUE THREAD

**Issue by foxhable** [aaccent/loginov_layout#31]
- При наведении в пустую зону должно закрываться меню

<details><summary>Скрин</summary>

![image](https://github.com/aaccent/loginov_layout/assets/36298346/29321aea-93aa-437a-8952-81862ccd1dc5)
</details> 

--- 

- Расстояния между элементами не по макету из-за минимальной высоты выпадающего меню.

<details><summary>Скрин</summary>

![image](https://github.com/aaccent/loginov_layout/assets/36298346/748a4e12-dba9-43c7-bebe-1bcfb57f52b6)
</details>

**Comment by EduardoAlparov** [comment]
Исправлено, нужно проверить

**Comment by foxhable** [comment]
Переключение категорий оказывается нужно сделать при наведении, а не по нажатию
