### ISSUE TITLE
Анимация текста в цитате

### ISSUE THREAD

**Issue by foxhable** [aaccent/loginov_layout#32]
- тут анимацию более плавную

<details><summary>Скрин</summary>

![image](https://github.com/aaccent/loginov_layout/assets/36298346/a535f77f-9724-472c-9503-621c10c955e3)
</details> 

---

- на странице "О компании" анимации нет

<details><summary>Скрин</summary>

![image](https://github.com/aaccent/loginov_layout/assets/36298346/ec5f60b4-a618-4ab8-8445-378e9f1e2204)
</details> 

---

- На мобиле ломается

<details><summary>Скрин</summary>

![image](https://github.com/aaccent/loginov_layout/assets/36298346/8c4b8f9c-dfd0-4790-b600-6c5ffad5a853)
</details>

**Comment by EduardoAlparov** [comment]
Исправлено, нужно проверить
