### ISSUE TITLE
Блок "Мост между Россией и Казахстаном"

### ISSUE THREAD

**Issue by foxhable** [aaccent/loginov_layout#33]
- Нет фото
- Убрать ссылку с "Офис находится в Казахстане"

<details><summary>Скрин</summary>

![image](https://github.com/aaccent/loginov_layout/assets/36298346/83fa03d1-89f2-4d4f-afd6-3374b360b517)
</details>

**Comment by EduardoAlparov** [comment]
Исправлено, нужно проверить
