### ISSUE TITLE
Слайдеры

### ISSUE THREAD

**Issue by foxhable** [aaccent/loginov_layout#34]
Слайдеры должны быть закциклены в блоках:
- "Отзывы о нашей работе"
- "Фотогалерея"

<details><summary>Скрин 1</summary>

![image](https://github.com/aaccent/loginov_layout/assets/36298346/d1734a77-4bae-4e5a-bc20-f2a2d2eab21d)
</details> 

<details><summary>Скрин 2</summary>

![image](https://github.com/aaccent/loginov_layout/assets/36298346/d866f342-7a32-4026-9bcc-cdc7a6d296f4)
</details>

**Comment by EduardoAlparov** [comment]
Исправлено, нужно проверить
