### ISSUE TITLE
Анимация списка партнеров

### ISSUE THREAD

**Issue by foxhable** [aaccent/loginov_layout#36]
анимацию нужно с примером сравнить, сдвиг должен быть плавный, а не целым блоком

<details><summary>Скрин</summary>

![image](https://github.com/aaccent/loginov_layout/assets/36298346/a97ff4e0-6822-483f-a72e-cb9bb3c39470)
</details>

**Comment by EduardoAlparov** [comment]
Исправлено, нужно проверить
