### ISSUE TITLE
Блок "Отзывы о нашей работе"

### ISSUE THREAD

**Issue by foxhable** [aaccent/loginov_layout#4]
1. Цвет текста даты в макете `#7E8397`, в верстке `#231f20`

![image](https://github.com/aaccent/loginov_layout/assets/36298346/cb115590-0818-4a25-a090-e8358a573605)

<br/>

2. Тоже самое с название услуги

![image](https://github.com/aaccent/loginov_layout/assets/36298346/4b690528-6390-48ac-bace-c5eecf388ce6)

<details><summary>Скрин блока</summary>

![image](https://github.com/aaccent/loginov_layout/assets/36298346/497bde8a-24ca-4ef5-b04c-d5e36037aba9)
</details>

**Comment by EduardoAlparov** [comment]
Исправлено, нужно проверить
