### ISSUE TITLE
Страница проекта

### ISSUE THREAD

**Issue by foxhable** [aaccent/loginov_layout#40]
- Отступы между текстами и заголовками не соответствуют макету. Вероятно ты захочешь сделать сначала #41 

<details><summary>Скрин</summary>

![image](https://github.com/aaccent/loginov_layout/assets/36298346/87763746-8d63-4c05-8383-5cd9a11e8049)
</details> 

---

- Дата должна быть под тэгами

<details><summary>Скрин</summary>

![image](https://github.com/aaccent/loginov_layout/assets/36298346/365d541f-9844-4045-8495-eaaf3de9c9bb)
</details>

**Comment by EduardoAlparov** [comment]
Исправлено, нужно проверить

**Comment by foxhable** [comment]
1. У `h3` должно быть `60px` сверху, в верстке `40px`

<details><summary>Скрин</summary>

![image](https://github.com/aaccent/loginov_layout/assets/36298346/ff1923e0-c0a8-4389-9905-7a4fdaec19fd)
</details> 

---

2. Для названия статьи нужно сделать отступ сверху в `13rem`

<details><summary>Скрин</summary>

![image](https://github.com/aaccent/loginov_layout/assets/36298346/e2bea3b7-ebc3-44f8-8128-478c07fe3535)
</details>

**Comment by foxhable** [comment]
Отступ названия статьи больше макета
