### ISSUE TITLE
Разметка контента

### ISSUE THREAD

**Issue by foxhable** [aaccent/loginov_layout#41]
На страницах 
- "Страница проекта"
- "Услуга"
- "Подуслуга"
- "Статья"

Нужно изменить разметку, т.к. контент менеджеры не всегда достаточно квалифицированы или внимательны.

### Правила:
- на `ul` не должно быть `style` атрибута, КМы не будут это указывать
- не должны вставляться декоративные элементы через `svg` и `img`, КМ будет вставлять только контент, он не будет заниматься визуалом.
- нельзя использовать атрибуты `class` и `id`
- не вкладывать ненужные `span` в `a` и `p`

### Примеры
<details><summary>Текущая разметка</summary>

```html
<ul>
  <li>
      <a href="#">
        <svg class="icon">
          <use xlink:href="./images/sprite.svg#arrow-forward"></use>
        </svg>
        <span>Получение РВП</span>
      </a>
  </li>
</ul>
```
</details> 

<details><summary>Должно быть</summary>

```html
<ul>
  <li>
    <a href="#">Получение РВП</a>
  </li>
</ul>
```
</details> 

За стилизовать этот список можно через псевдо-селектор `:has`

```css
ul:has(li a) li::before {
  background-image: '';
}
```

---

<details><summary>Текущая</summary>

```html
<p>
  <span>
    Задача организации, в особенности же начало повседневной 
    работы по формированию позиции позволяет выполнять важные 
    задания по разработке дальнейших направлений развития.
  </span>

  <span>
    Жирмунский, однако, настаивал, что синхрония доступна. 
    Анжамбеман семантически отражает хорей в кругу.
  </span>
</p>
```
</details> 

<details><summary>Должно быть</summary>

```html
<p>
  Задача организации, в особенности же начало повседневной
  работы по формированию позиции позволяет выполнять важные
  задания по разработке дальнейших направлений развития.
</p>

<p>
  Жирмунский, однако, настаивал, что синхрония доступна.
  Анжамбеман семантически отражает хорей в кругу.
</p>
```
</details> 

--- 

<details><summary>Текущая</summary>

```html
<ul style="list-style-position: inside;list-style-type: disc">
  <li><span>Дистанционная работа</span></li>
  <li><span>Доступные цены</span></li>
  <li><span>Работаем соблюдая законодательство</span></li>
  <li><span>Индивидуальный подход к проблеме</span></li>
</ul>
```
</details> 

<details><summary>Должно быть</summary>

```html
<ul>
  <li>Дистанционная работа</li>
  <li>Доступные цены</li>
  <li>Работаем соблюдая законодательство</li>
  <li>Индивидуальный подход к проблеме</li>
</ul>
```
</details> 

---

Возможно отказаться от `div` и использовать `margin-top` на `h*` тэгах для разделения блоков текста. Если невозможно, то необязательно

**Comment by EduardoAlparov** [comment]
с img тэгом подскажи как надо, остальное можно проверить

**Comment by foxhable** [comment]
С картинкой ок, их то можно вставлять и так и через `figure`, я про `img` в списках говорил. 

Нужно ещё генерацию ссылок тоже сделать автоматической парся `h3` и `h2` заголовки. КМы либо пропустят этот момент, либо могут не разобраться
Сам заголовок страницы статьи сделай `h1` тэгом, не понимаю почему дизайнер сделал `h2`

https://github.com/aaccent/loginov_layout/blob/21388f995e5a85e9b0b45ce2f2f366b624aba49b/js/modules/articleNavRender.js#L10-L13

---

На странице услуги и подуслуги `span` элементы в `p` тоже нужно убрать. Заголовки страниц сделать `h1`

--- 
На странице проекта заголовок тоже `h1`
