### ISSUE TITLE
Выбор номера на мобилке

### ISSUE THREAD

**Issue by foxhable** [aaccent/loginov_layout#44]
- `.contact__phone` должен быть `a` тэгом

![image](https://github.com/aaccent/loginov_layout/assets/36298346/e1beedd0-4b71-4958-bb42-368bdfd704c6)

- После выбора номера в попапе номеров - попап должен закрыться, номер в шапке поменяться и цвет у надписи "Москва" поменяться.

![image](https://github.com/aaccent/loginov_layout/assets/36298346/6196220a-3d73-4aad-b0f9-1e9e52435fe9)

**Comment by EduardoAlparov** [comment]
Исправлено, нужно проверить

**Comment by foxhable** [comment]
`.contact__phone` должна быть ссылкой
