### ISSUE TITLE
Декоративный фон

### ISSUE THREAD

**Issue by foxhable** [aaccent/loginov_layout#45]
На странице "Подуслуга" в блоке с темном фоном декоративный вектор должен быть сверху блока

<details><summary>Сравнение</summary>

![image](https://github.com/aaccent/loginov_layout/assets/36298346/16a8cf31-c19a-40a1-9212-5bdfe45463d1)
</details>

**Comment by EduardoAlparov** [comment]
Исправлено, нужно проверить
