### ISSUE TITLE
Абсолютные пути

### ISSUE THREAD

**Issue by foxhable** [aaccent/loginov_layout#5]
Смени абсолютные пути на относительные. Абсолютные пути заставляют сборщиков размещать в корне сайта папки или менять пути вручную. Относительные позволяют разместить папки со стилями куда угодно. Плюс в github pages они не работают, т.к. корень сайта находится в подпапке

https://github.com/aaccent/loginov_layout/blob/5fbbd31a63f3d047c7335bb2068e2f5b9dc8f8de/scss/content/_fonts.scss#L5-L6

**Comment by EduardoAlparov** [comment]
Исправлено, нужно проверить
