### ISSUE TITLE
Анимация в футере

### ISSUE THREAD

**Issue by foxhable** [aaccent/loginov_layout#52]
анимацию не поменяли в футере

При появлении футера на экране прорисовывается вектор, 1 раз, без зацикливаний, [как тут](https://www.aaccent.ru/), на пунктир не смотрим

<details><summary>Details</summary>

![image](https://github.com/aaccent/loginov_layout/assets/36298346/177e72c9-f1b5-4f69-9342-0f0037833fdd)
</details>

**Comment by EduardoAlparov** [comment]
Исправлено, нужно проверить
