### ISSUE TITLE
Выбор номера на мобилке

### ISSUE THREAD

**Issue by foxhable** [aaccent/loginov_layout#53]
- При смене номера на Казахстан круг должен стать желтым.

<details><summary>Скрин</summary>

![image](https://github.com/aaccent/loginov_layout/assets/36298346/cc43b5ac-234e-4fd4-9767-d544165abb37)
</details> 

---

При смене номера на мобилке не нужно дожидаться анимации смены - сразу закрывать попап

**Comment by EduardoAlparov** [comment]
Исправлено, нужно проверить
