### ISSUE TITLE
Селектор на мобилке

### ISSUE THREAD

**Issue by foxhable** [aaccent/loginov_layout#56]
Селектор, который раскрывается на пк, на мобилке должен раскрываться в попапе. При выборе пункта так-же закрытие

<details><summary>Скрин селектора</summary>

![image](https://github.com/aaccent/loginov_layout/assets/36298346/0364fcaf-a5e1-4236-883b-694e38b3559c)
</details> 

<details><summary>Скрин попапа</summary>

![image](https://github.com/aaccent/loginov_layout/assets/36298346/c976a7c8-3af0-4e77-90f1-9d607729e1af)
</details>

**Comment by EduardoAlparov** [comment]
Исправлено, нужно проверить
