### ISSUE TITLE
Блок "Этапы работы"

### ISSUE THREAD

**Issue by foxhable** [aaccent/loginov_layout#6]
Цвет текста элементов в макете `#7E8397`, в верстке `#231f20`

![image](https://github.com/aaccent/loginov_layout/assets/36298346/06fe7b6b-e78c-48f1-8362-2ba786ffe473)

<details><summary>Скрин блока</summary>

![image](https://github.com/aaccent/loginov_layout/assets/36298346/4a14c5cf-a3e5-4a0f-99ac-5909d904a586)
</details>

**Comment by EduardoAlparov** [comment]
Исправлено, нужно проверить
