### ISSUE TITLE
Блок с формой

### ISSUE THREAD

**Issue by foxhable** [aaccent/loginov_layout#7]
1. Толщина текста должна быть `500`

![image](https://github.com/aaccent/loginov_layout/assets/36298346/5786b743-e3e2-4448-a1e0-a8eee3a30ae7)

<details><summary>Скрин блока</summary>

![image](https://github.com/aaccent/loginov_layout/assets/36298346/92c9eaba-855d-4882-a971-fbd4549ecf12)
</details> 

---

2. Отступ между полоской и формой должен быть `20px`

<details><summary>Скрин</summary>

![image](https://github.com/aaccent/loginov_layout/assets/36298346/c98c7f74-3feb-49ed-aced-58c83a5388e5)
</details>

**Comment by EduardoAlparov** [comment]
Исправлено, нужно проверить
