### ISSUE TITLE
Мобильное меню

### ISSUE THREAD

**Issue by foxhable** [aaccent/loginov_layout#8]
1. Нет расстояния в `15px` снизу

<details><summary>Скрин</summary>

![image](https://github.com/aaccent/loginov_layout/assets/36298346/73f4aa62-e553-4548-8510-6158179de584)
</details> 

---
- Кнопка "Заказать звонок" ничего не делает

**Comment by EduardoAlparov** [comment]
Исправлено, нужно проверить
